# cribbed from:
# http://hermit.no/github-actions-including-how-to-build-net-framework-projects/#then-the-legacy-format

name: blaise-nuget-api.CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1
  
    # Runs a single command using the runners shell
    - name: Run msbuild
      run: msbuild Blaise.Nuget.Api.sln -p:Configuration=Release

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Build complete
        echo RUn tests now?
